### ISSUE TITLE
Receive timeout is not working

### ISSUE THREAD

**Issue by DrTon** [steveturner/netty-transport-purejavacomm#1]
Need to add in https://github.com/steveturner/netty-transport-purejavacomm/blob/develop/src/main/java/com/beauhinks/purejavacomm/PureJavaCommChannel.java#L68

```
        serialPort.enableReceiveTimeout(config().getOption(READ_TIMEOUT));
```

**Comment by steveturner** [comment]
Wow... thanks! So sorry it took me long to get to this. Will work it in!
